name: test
runs:
  using: "composite"
  steps:
  - name: step1
    shell: bash
    if: contains(github.job, 'build')
    run: |
      echo "printing build job"
    
  - name: step2
    shell: bash
    if: contains(github.job, 'deploy')
    run: |
      echo "printing deplo job"
