name: uipath-upload-download

on:
  issues:
    types:
      - closed

jobs:
  uipath-deploy:
    runs-on: ubuntu-latest
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository content
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.head_ref }}
        #   # full git history is needed to get a proper list of changed files.
        #   fetch-depth: 0
        
      - name: Extract issue details
        shell: bash
        run: |
          # Extract the YAML portion of the issue body
          yaml_content=$(awk '/```yaml/{flag=1; next}/```/{flag=0}flag' <<< "${{ github.event.issue.body }}")
          
          # Extract values from the YAML content using jq
          process_name=$(echo "${yaml_content}" | jq -r '.process_name')
          process_version=$(echo "${yaml_content}" | jq -r '.process_version')
          change_reason=$(echo "${yaml_content}" | jq -r '.change_reason')

          echo "Process Name: $process_name"
          echo "Process Version: $process_version"
          echo "Change Reason: $change_reason"

      # - name: Check issue title
      #   if: ${{ github.event.issue.title == 'Issue: Production package move request' }}
      #   run: echo "Issue title matches"

      # - name: Extract issue details
      #   # if: ${{ github.event.issue.title == 'Issue: Production package move request' }}
      #   run: |
      #     echo "process_name=$(awk -F ': ' '/process_name:/ {print $2}' <<< ${{ github.event.issue.body }})" >> $GITHUB_ENV
      #     echo "process_version=$(awk -F ': ' '/process_version:/ {print $2}' <<< ${{ github.event.issue.body }})" >> $GITHUB_ENV
      #     echo "change_reason=$(awk -F ': ' '/change_reason:/ {print $2}' <<< ${{ github.event.issue.body }})" >> $GITHUB_ENV

      # - name: Download & upload package
      #   shell: bash
      #   run: |
      #     echo "PROCESS_NAME: $PROCESS_NAME"
      #     echo "PROCESS_VERSION: $PROCESS_VERSION"
      #     echo "CHANGE_REASON: $CHANGE_REASON"
      #     # pip3 install requests
      #     # python upload-download-package.py "${{ inputs.package-and-version }}"
      #   env:
      #     # DEV_CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }} 
      #     # DEV_CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }} 
      #     # TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }} 
      #     # TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
      #     PROCESS_NAME: ${{ env.process_name }}
      #     PROCESS_VERSION: ${{ env.process_version }}
      #     CHANGE_REASON: ${{ env.change_reason }}
