name: CI/CD 

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run step1
        uses: SahanaGowdaBV/github_Job_name_variable/.github/actions/pass@main

  deploy:
    if: ${{ github.ref, 'refs/heads/hotfix-bug' || github.head_ref, 'refs/heads/hotfix-bug' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run step2
        uses: SahanaGowdaBV/github_Job_name_variable/.github/actions/pass@main
